name: laravel-api
services:
    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: laravel-api-php
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
            #secrets:
            #    - composer_auth
        restart: unless-stopped
#        ports:
#            - 5173:5173
        volumes:
            - .:/var/www:cached
            - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            #- ./.docker/php/supervisor:/var/run/supervisor
            - ./.docker/php/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
        environment:
            PHP_IDE_CONFIG: serverName=laravel-api
            APP_ENV: ${APP_ENV:-production}
        depends_on:
            - db


    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: laravel-api-nginx
        image: nginx
        restart: unless-stopped
        ports:
            - 8088:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .docker/logs:/var/log/php
        depends_on:
            - php

    #composer:
    #    image: composer:lts
    #    container_name: laravel-api-composer
    #    volumes:
    #        - .:/var/www
    #    working_dir: /var/www
    #    command: bash -c "composer install"

    # ####################################################################################################
    # # DATABASE (MariaDB)
    # ####################################################################################################
    db:
        image: mariadb
        container_name: ${DB_HOST:-laravel-api-db}
#        ports:
#            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/logs:/var/log/mysql
        environment:
            #MARIADB_ROOT_PASSWORD: root
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-laravel}
            MYSQL_USER: ${MYSQL_USER:-laravel}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-laravel}

    swagger-editor:
        image: swaggerapi/swagger-editor
        container_name: laravel-api-swagger
        ports:
            - 8080:8080
        volumes:
            - ./openapi.yaml:/openapi.yaml
        environment:
            SWAGGER_FILE: /openapi.yaml

networks:
    default:
        name: laravel-api
